### ISSUE TITLE
PdoBackend doesn't work with non persistent caches

### ISSUE THREAD

**Issue by kitsunet** [flownative/beach-flow-companion#6]
Due to it's reliance on injection the included PdoBackend does not work with non persistent caches as those are flushed in compile time mode. A possible quickfix that at least helps with the problem is to throw an exception if the backend is used and no persistence optoins were injected.

**Comment by kdambekalns** [comment]
It seems the "vanilla" PdoBackend also has a problem, even with persistent caches. Using this (with Flow 5.2):

```yaml
Flow_Security_Cryptography_HashService:
  backend: Neos\Cache\Backend\PdoBackend
  backendOptions:
    dataSourceName: 'mysql:host=%env:BEACH_DATABASE_HOST%;dbname=%env:BEACH_DATABASE_NAME%'
    username: '%env:BEACH_DATABASE_USERNAME%'
    password: '%env:BEACH_DATABASE_PASSWORD%'
    defaultLifetime: 0
  persistent: true
```

still leads to this:

```
beach@instance-something:/application$ ./flow flow:cache:list
Unknown column type "flow_json_array" requested.
Any Doctrine type that you use has to be registered with
\Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known
types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs
during database introspection then you might have forgotten to register
all database types for a Doctrine Type. Use
AbstractPlatform#registerDoctrineTypeMapping() or have your custom types
implement Type#getMappedDatabaseTypes(). If the type name is empty you
might have a problem with the cache or forgot some mapping information.

  Type: Doctrine\DBAL\DBALException
  File: Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php
  Line: 283
```
